# Generated by Django 3.2 on 2022-02-05 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='craeted_on',
            new_name='created_on',
        ),
    ]
